[build]
target = "x86_64-nuclea_r_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[unstable]
build-std = ["alloc", "compiler_builtins", "core"]
build-std-features = ["compiler-builtins-mem"]